### ISSUE TITLE
Line magic not registering correctly

### ISSUE THREAD

**Issue by fperez** [yuvipanda/gh-scoped-creds#17]
I can't debug right now, but after uninstalling my fork from the hub and trying to use the system-wide one, I'm getting:

![image](https://user-images.githubusercontent.com/57394/163919985-1e004cfb-b499-424e-827a-5e113b72bd12.png)

Does it work for you?

**Comment by yuvipanda** [comment]
@fperez ah, I hadn't updated the README - it's %ghscopedcreds, not %ghscopedauth
