### ISSUE TITLE
Feedback on README.md instructions

### ISSUE THREAD

**Issue by consideRatio** [yuvipanda/gh-scoped-creds#2]
1. Step 6 in the [GitHub App configuration, part of the README.md](https://github.com/yuvipanda/github-app-user-auth#github-app-configuration) includes:

   > Save the Public link as well, as users will need to use this to grant access to particular repositories.

   What does this refer to?
   
2. Step 1 in the [Client configuration, part of the README.md](https://github.com/yuvipanda/github-app-user-auth#client-configuration) refers to use of `git-credentials-store`. Since that is a technical reference, I'd expect a link or similar to be able to understand if that was a Python package we depend on, an `apt-get` package, or something part of what you get when installing `git` in any way etc.

   Is it correct that `git-credentials-store` refers to something shipping with `git`, namely [this](https://git-scm.com/docs/git-credential-store).
   
3. Use of `GITHUB_APP_CLIENT_ID`, maybe `GITHUB_APP_USER_AUTH_CLIENT_ID` or `GITHUB_APP_USER_AUTH__CLIENT_ID` instead?
   I've seen a lot of confusion stemming from not knowing what environment variables influence what software. By prefixing the environment variable with the related software's full name, there is a lot less confusion about it. To me, that far outweighs the downside of having a longer environment variable name.
   
   What do you think about renaming this env var?

**Comment by yuvipanda** [comment]
Great feedback, @consideRatio!

(1) refers to this:

<img width="557" alt="image" src="https://user-images.githubusercontent.com/30430/151035298-2eca0333-5bba-44a3-a000-aa11229a7d54.png">

This is the link used by users to 'install' the app to grant it access to particular repos.

For (2), adding the link seems a great idea.

For (3), +1 - let's change it now, it's early enough that we have control of all the major deployments :D I like `GITHUB_APP_USER_AUTH_CLIENT_ID`

**Comment by consideRatio** [comment]
:tada: thanks for the clarifications and project!

About renaming the environment variable. Perhaps we can rename also the suggested filename as well? From `--file=/tmp/github-app-git-credentials` to `--file=/tmp/github-app-user-auth-git-credentials`.

**Comment by yuvipanda** [comment]
yep, both sound like great ideas. Do you think you can make a quick PR, @consideRatio?

**Comment by consideRatio** [comment]
Speaking of renaming. I also consider a project name like `github-tmp-scoped-user-auth` or `github-tmp-user-auth`?

The fact that we rely on a GitHub application feels less relevant to convey than that what is enabled for the by using this - temporary, scoped, github credentials.

**Comment by yuvipanda** [comment]
I've done the following:

1. Renamed the project to gh-scoped-creds!
2. Made the environment variable be GH_SCOPED_CREDS_CLIENT_ID so it's not super generic
3. The appropriate gitconfig entry is now automatically set (https://github.com/yuvipanda/gh-scoped-creds/pull/14) so admins no longer need to configure it.
4. I've linked to git-credentials-store from the README.

I think the public app 'install' link can be made more discoverable, but you've already opened #4 - so I'm going to close this one. THANK YOU SO MUCH for making the project better! <3

**Comment by consideRatio** [comment]
Wieee nice work!!
