### ISSUE TITLE
Helpful message on public url to app, configured like _CLIENT_ID

### ISSUE THREAD

**Issue by consideRatio** [yuvipanda/gh-scoped-creds#4]
I've not gone through the full steps, but wouldn't it be nice to have a standardized UX for how users would go about knowing what app to authorize against etc?

I figure we would configure the public url (in my case https://github.com/settings/apps/hub-jupytearth-org-github-integ), just like we configure the GITHUB_APP_CLIENT_ID env var. While it isn't crucial, it would allow this software to provide helpful messages to the user if they aren't already setup or similar maybe?

Another options would perhaps be to let this software lookup the public URL by knowing the APP id by asking some GitHub API?

**Comment by yuvipanda** [comment]
Yah, asking the GitHub API and providing that URL would be perfect. If not, it would definitely be great to allow that to be ocnfigured.
